spring:
  datasource:
    url: jdbc:mysql://${HOME}/todo
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${USERNAME}
    password: ${PW}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        use_sql_comments: true
    defer-datasource-initialization: true
  mail:
    host: smtp.gmail.com # 1
    port: 587 # 2
    username: ${MAIL.USERNAME} # 3
    password: ${MAIL.PW} # 4
    properties:
      mail:
        smtp:
          auth: true # 5
          timeout: 5000 # 6
          starttls:
            enable: true # 7
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}


jwt:
  secret:
    key: ${JWT}
